### ISSUE TITLE
Is SLIP header standard ? Not defined in RFC 1055

### ISSUE THREAD

**Issue by adetante** [mvertescher/serial-line-ip-rs#5]
Thank you for your work on this lib. 

I'm surprised to see the header added at the beginning of the frame. For me, the frame starts only with an END character followed by the data (see https://tools.ietf.org/html/rfc1055). 

Am I missing something?

**Comment by adetante** [comment]
With [this patch](https://github.com/adetante/serial-line-ip-rs/commit/d3a4842c68a5bbbfdf7338381790bd8b07eaf1f8), lib is conform with RFC 1055

**Comment by mvertescher** [comment]
Hey @adetante, thanks for opening this issue and making a patch!

You're totally right that the header is incorrect currently and your fix looks good to me.

Mind opening a PR so I can merge your patch?

**Comment by adetante** [comment]
Thanks @mvertescher for your quick answer!
Here is the PR https://github.com/mvertescher/serial-line-ip-rs/pull/6
